// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SiteWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SiteWeb.Models.Details", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("NichoirId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NichoirId");

                    b.ToTable("Details");
                });

            modelBuilder.Entity("SiteWeb.Models.Nichoir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ChipId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Emplacement")
                        .HasMaxLength(140)
                        .HasColumnType("varchar(140)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("nichoirs", (string)null);
                });

            modelBuilder.Entity("SiteWeb.Models.RessourceMedia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Chemin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("DetailsId")
                        .HasColumnType("int");

                    b.Property<int>("NichoirId")
                        .HasColumnType("int");

                    b.Property<string>("Trigger")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("DetailsId");

                    b.HasIndex("NichoirId");

                    b.ToTable("ressources_media", (string)null);
                });

            modelBuilder.Entity("SiteWeb.Models.Details", b =>
                {
                    b.HasOne("SiteWeb.Models.Nichoir", "Nichoir")
                        .WithMany()
                        .HasForeignKey("NichoirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nichoir");
                });

            modelBuilder.Entity("SiteWeb.Models.RessourceMedia", b =>
                {
                    b.HasOne("SiteWeb.Models.Details", null)
                        .WithMany("Medias")
                        .HasForeignKey("DetailsId");

                    b.HasOne("SiteWeb.Models.Nichoir", null)
                        .WithMany()
                        .HasForeignKey("NichoirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SiteWeb.Models.Details", b =>
                {
                    b.Navigation("Medias");
                });
#pragma warning restore 612, 618
        }
    }
}
